### ISSUE TITLE
不支持设置AllowAutoRedirect

### ISSUE THREAD

**Issue by ddgweb** [JasonSoft-Net/JsHttpClient#1]
不支持设置AllowAutoRedirect

**Comment by jasonsoft-net** [comment]
是吧，我最近看一下，更新一下

**Comment by jasonsoft-net** [comment]
// 是否允许自动重定向功能，如果不需要，请使用以下方式，默认允许为 true
// Allow Auto Redirect Property, The default value is true
services.AddJsHttpClient(new JsHttpClientOptions{ AllowAutoRedirect = false });
